version: "3.8"

networks:
  common-network:
    driver: bridge

services:
  db:
    image: "postgres:14"
    networks:
      - common-network
    restart: "always"
    hostname: postgres
    container_name: scan-connect-db
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "scan-connect"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"